/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Beings from "./script/Beings"
import Bullet from "./script/Bullet"
import Hero from "./script/Hero"
import Monster from "./script/Monster"
import Thing from "./script/Thing"
import Hero_Bullet from "./script/Hero_Bullet"
import Monster_Bullet from "./script/Monster_Bullet"
import Gate from "./script/Gate"
import wall from "./script/wall"

import Monster_Bullet_basic1 from "./script/Monster_Bullet_basic1"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
        
        reg("script/Object.js",Beings);
		reg("script/Bullet.js",Bullet);
		reg("script/Hero.js",Hero);
		reg("script/Monster.js",Monster);
		reg("script/Thing.js",Thing);
		reg("script/Hero_Bullet.js",Hero_Bullet);
		reg("script/Monster_Bullet.js",Monster_Bullet);
		reg("script/Gate.js",Gate);
        reg("script/wall.js",wall);

        reg("script/Monster_Bullet_basic1.js", Monster_Bullet_basic1);
    }
}

GameConfig.width = 640;
GameConfig.height = 1136;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "test/TestScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
